networks:
  user-management:
    name: user-management
    driver: bridge

services:

  userdb:
    image: mysql:8.0.39
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"  # host:container
    networks:
      - user-management
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - user-management
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - user-management
    restart: unless-stopped

  usermgmt:
    image: harshitshankar1998/usermgmt-app:latest
    container_name: usermgmt
    depends_on:
      - userdb
      - kafka
    ports:
      - "8081:8080"
    networks:
      - user-management
    restart: unless-stopped
