version: '3.9'

networks:
  user-management:
    driver: bridge

services:
  # MySQL database (no init SQL file)
  userdb:
    image: mysql:8.0.39
    container_name: userdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    # no --init-file here (you asked to remove init file setup)
    ports:
      - "3307:3306"     # connect from host to port 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - user-management

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - user-management

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - user-management

  # Your Spring Boot App
  usermgmt:
    image: harshitshankar1998/usermgmt-app:latest
    container_name: usermgmt
    restart: always
    depends_on:
      - userdb
      - kafka
    ports:
      - "8081:8080"     # access app on localhost:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://userdb:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - user-management
